name: Upload to Workshop

on:
  workflow_dispatch:
    inputs:
      itemid:
        description: "The steam workshop item id to publish artifacts for"
        required: false
        default: ""
        type: choice
        options:
          - "2898069883" # KitchenLib mod id
          - "2932799348" # KitchenLib Beta mod id
      releaseversion:
        description: "The release version"
        required: true
        default: ""
        type: string
      betaversion:
        description: "The beta version"
        required: false
        default: ""
        type: string
      plateupsignature:
        description: "PlateUp provided signature"
        required: false
        default: ""
        type: string
      publishtodiscord:
        type: boolean
        description: "Publish release note to Discord"
        default: true
      publishtosteam:
        type: boolean
        description: "Publish update to Steam"
        default: true

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Release
        id: download-release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          preRelease: true
          tag: "v${{ github.event.inputs.releaseversion }}${{ github.event.inputs.betaversion }}"
          fileName: "KitchenLib-v${{ github.event.inputs.releaseversion }}${{ github.event.inputs.betaversion }}.zip"
