name: Upload to Workshop

on:
  workflow_dispatch:
    inputs:
      itemid:
        description: "The steam workshop item id to publish artifacts for"
        required: false
        default: ""
        type: choice
        options:
          - "3299022422" # KitchenLib mod id
      releaseversion:
        description: "The release version"
        required: true
        default: ""
        type: string
      betaversion:
        description: "The beta version"
        required: false
        default: ""
        type: string
      publishtodiscord:
        type: boolean
        description: "Publish release note to Discord"

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Display structure of downloaded files
        run: |
          echo hi1
          ls -l
          echo hi2
